name: "[DEMO] Generate Load on crAPI"
on:
  workflow_dispatch:
    inputs:
      target:
        type: string
        description: "Target URL"
        required: true

jobs:
  loadgen:
    strategy:
      matrix:
        run_id: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - uses: levoai/actions/test-plan@main
        with:
          plan: "continuous_testing_levo_ai_auth0:ws/continuous_testing:app/crapi_loadgen_demos:tp/crapi_loadgen_demos"
          base64_env: ${{ secrets.CRAPI_ENV_BASE64 }}
          authorization-key: ${{ secrets.LEVO_CLI_AUTH_KEY }}
          organization-id: ${{ secrets.LEVO_CI_ORGANIZATION_ID }}
          target: ${{ inputs.target }}
          fail-on-failed-tests: false
          saas-url: https://api.dev.levo.ai
          report: false
          cli_extra_args: "-v INFO"
