name: Generate Load on crAPI
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      crapi_url:
        type: string
        description: "crAPI URL"
        required: false

env:
  CRAPI_URL: ${{ inputs.crapi_url || 'http://34.170.155.55' }}

jobs:
  loadgen:
    runs-on: ubuntu-latest
    steps:
      - uses: levoai/actions/test-plan@main
        with:
          plan: "continuous_testing_levo_ai_auth0:ws/continuous_testing:app/crapi_loadgen:tp/crapi_loadgen1"
          base64_env: ${{ secrets.CRAPI_ENV_BASE64 }}
          authorization-key: ${{ secrets.LEVO_CLI_AUTH_KEY }}
          organization-id: ${{ secrets.LEVO_CI_ORGANIZATION_ID }}
          target: ${{ env.CRAPI_URL }}
          fail-on-failed-tests: false
          saas-url: https://api.dev.levo.ai
          report: false
          cli_extra_args: "-v INFO"
